postgresql:
  SecretName: ""
  installdep:
    enable: false
  endpoint:
    external: true
    address: db-postgresql.default.svc.cluster.local
    port: 5432
    user: postgres
    dbName: reportportal

# ingress configuration for the ui
ingress:
  hosts:
    - reportportal.k8.com

# node selector for all components, if any
nodeSelector:
  enabled: false
  selector:
    reportportal: true